# Generated by Django 4.2.9 on 2024-04-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savini', '0004_remove_userdata_password_userdata_encrypted_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='encrypted_password',
            new_name='password',
        ),
    ]
