# Generated by Django 4.2.9 on 2024-04-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savini', '0008_remove_userprofile_user_remove_userdata_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='encrypted_password',
            new_name='password',
        ),
    ]
